<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class AddNewsRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'required|string',
            'content' => 'required|string',
        ];
    }
    public function messages()
    {
        return [
            'title.required' => 'Ce champ est vide',
            'title.string' => 'Contenu incorrect',
            'content.required' => 'Ce champ est vide',
            'content.string' => 'Contenu incorrect',
        ]; // TODO: Change the autogenerated stub
    }
}
