<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CreateDishRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'dishName' => 'required|max:100',
            'dishCal' => 'required|integer',
            'dishQuant' => 'required|integer',
            'dishPro' => 'integer',
            'dishLip' => 'integer',
            'dishGlu' => 'integer',
        ];
    }

    public function messages()
    {
        return [
            'dishName.required' => 'Ce champ est requis',
            'dishCal.required' => 'Ce champ est requis',
            'dishQuant.required' => 'Ce champ est requis',
            'dishName.max' => 'Le nom est trop long',
            'dishCal.integer' => 'La valeur doit être numérique',
            'dishQuant.integer' => 'La valeur doit être numérique',
            'dishPro.integer' => 'La valeur doit être numérique',
            'dishLip.integer' => 'La valeur doit être numérique',
            'dishGlu.integer' => 'La valeur doit être numérique',
        ]; // TODO: Change the autogenerated stub
    }
}
