<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CreateFoodRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'foodName' => 'required|max:100',
            'foodCal' => 'required|integer',
            'foodQuant' => 'required|integer',
            'foodPro' => 'integer',
            'foodLip' => 'integer',
            'foodGlu' => 'integer',
        ];
    }

    public function messages()
    {
        return [
            'foodName.required' => 'Ce champ est requis',
            'foodCal.required' => 'Ce champ est requis',
            'foodQuant.required' => 'Ce champ est requis',
            'foodName.max' => 'Le nom est trop long',
            'foodCal.integer' => 'La valeur doit être numérique',
            'foodQuant.integer' => 'La valeur doit être numérique',
            'foodPro.integer' => 'La valeur doit être numérique',
            'foodLip.integer' => 'La valeur doit être numérique',
            'foodGlu.integer' => 'La valeur doit être numérique',
        ]; // TODO: Change the autogenerated stub
    }
}
