<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class LoginRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'email' => 'required|string|email',
            'password' => 'required|string|min:8',
        ];
    }
    public function messages()
    {
        return [
            'email.required' => 'Ce champ est vide',
            'email.email' => 'Format incorrect',
            'password.required' => 'Ce champ est vide',
            'password.min' => 'Votre mot de passe doit faire :min caractères',
            'email.string' => 'Format incorrect',
            'password.string' => 'Format incorrect',
        ]; // TODO: Change the autogenerated stub
    }
}
